# Generated by Django 2.2.4 on 2021-03-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('dose', models.CharField(max_length=20)),
                ('intake_method', models.CharField(choices=[('OR', 'Oral'), ('INJ', 'Injection'), ('RE', 'Rectal'), ('PA', 'Patch'), ('GE', 'Gel'), ('IH', 'Inhaling'), ('OC', 'Ocular')], max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
                ('end_date', models.DateTimeField(null=True)),
                ('notes', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('preferred_name', models.CharField(max_length=20)),
                ('pronouns', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doseage', models.CharField(max_length=60)),
                ('frequency', models.CharField(max_length=25)),
                ('quantity', models.CharField(max_length=35)),
                ('refills', models.IntegerField()),
                ('date_filled', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rx_given', to='main_app.User')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rxs', to='main_app.Medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_prescriptions', to='main_app.User')),
            ],
        ),
    ]
