# Generated by Django 2.2.4 on 2021-03-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='end_date',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
