# Generated by Django 2.2.4 on 2021-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210330_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='common_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
