# Generated by Django 2.2.4 on 2021-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_medication_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='starting_count',
            field=models.IntegerField(null=True),
        ),
    ]
